name: Auto Build ChinaIPs

on:
  schedule:
    - cron: '06 18 * * *' # 北京时间02:06 
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # 允许孤儿分支强制推送
      actions: write  # 允许 v7 插件删除日志

    steps:
      - name: 动态获取并下载最新版 Mihomo 内核
        run: |
          # 提取最新版本号
          LATEST_VERSION=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "🤖 探测到 Mihomo 最新版本: $LATEST_VERSION"
          
          # 拼接并下载
          DOWNLOAD_URL="https://github.com/MetaCubeX/mihomo/releases/download/${LATEST_VERSION}/mihomo-linux-amd64-${LATEST_VERSION}.gz"
          echo "🔗 开始下载: $DOWNLOAD_URL"
          
          curl -L -o mihomo.gz "$DOWNLOAD_URL"
          gunzip mihomo.gz
          chmod +x mihomo

      - name: 下载第三方规则
        run: |
          curl -L -o china_ip.yaml "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs_IP.yaml"

      - name: 编译mrs
        run: |
          ./mihomo convert-ruleset ipcidr yaml china_ip.yaml ChinaIPs.mrs

      - name: 新建孤儿分支并强制覆盖auto分支
        run: |
          mkdir publish
          mv *.mrs publish/
          cd publish
          
          git init
          git checkout --orphan auto
          
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          
          git add *.mrs
          git commit -m "🤖 规则编译更新: $(date +'%Y-%m-%d %H:%M:%S')"
          
          git push -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git auto
          
      - name: 清理 Actions 历史日志
        uses: igorjs/gh-actions-clean-workflow@v7
        with:
          workflow_names: "Auto Build ChinaIPs"
          runs_older_than: 0
          runs_to_keep: 3 # 面板永远只保留最近 3 天的绿灯记录
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}